package com.catalog.common.entity;

import jakarta.persistence.Column;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Base class for common entity fields.
 *
 * Any entity that extends this class will automatically get:
 * - id
 * - createdAt
 * - updatedAt
 *
 * Example:
 * public class Product extends BaseEntity { ... }
 */
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity {

    /**
     * Primary key for all entities.
     *
     * UUID is useful because it avoids predictable incremental IDs
     * and works well in distributed systems.
     */
    @Id
    @GeneratedValue
    @Column(nullable = false, updatable = false)
    private UUID id;

    /**
     * Automatically filled when the entity is first saved.
     *
     * Requires @EnableJpaAuditing in configuration.
     */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Automatically updated whenever the entity is modified.
     *
     * Requires @EnableJpaAuditing in configuration.
     */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Getter for entity ID.
     *
     * No setter is provided because ID should be generated by the database/JPA.
     */
    public UUID getId() {
        return id;
    }

    /**
     * Getter for creation timestamp.
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Getter for last update timestamp.
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }
}